/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Frames;

import byui.cit260.LostOnAnIsland.Lost.GameRun;
import byui.cit260.LostOnAnIsland.control.ChallengeControl;
import byui.cit260.LostOnAnIsland.view.CaveChallenge;
import byui.cit260.LostOnAnIsland.view.ForrestChallenge;
import byui.cit260.LostOnAnIsland.view.MapMenu;

import byui.cit260.LostOnAnIsland.view.RiverChallenge;

import byui.cit260.LostOnAnIsland.view.SwampChallenge;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;


/**
 *
 * @author bethanytaylor
 */
public class MapFrame extends javax.swing.JFrame {
    
    

    /**
     * Creates new form MapFrame
     */
    public MapFrame() {
        initComponents();
        
        for (int i = 0; i < 8; i++){
            if (!GameRun.getGame().getVisited(i)){
                continue;
            }
            switch (i){
                case 1: 
                    break;
                case 2: 
                    forestFrame.setEnabled(false);
                    break;
                case 3:
                    RiverFrame.setEnabled(false);
                    break; 
                case 4:
                    break;
                case 5:
                    break;
                case 6: 
                    break;
                case 7:
                    TreehouseFrame.setEnabled(false);
                    break;
                case 8:
                    break;
                case 0: 
                default: 
                    continue;
            }
        }

    }
    
    

    public JLabel getTime1() {
        return time;
    }

    public void setTime1(JLabel time) {
        this.time = time;
    }

    public JLabel getLogs() {
        return logs;
    }

    public void setLogs(JLabel logs) {
        this.logs = logs;
    }

    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        blah = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CaveFrame = new javax.swing.JButton();
        RiverFrame = new javax.swing.JButton();
        jbSwamp = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        forestFrame = new javax.swing.JButton();
        TreehouseFrame = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        shoreFrame = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logs = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        blah.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Marlett", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Map");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rsz_1island2.jpg"))); // NOI18N

        CaveFrame.setText("Cave");
        CaveFrame.setToolTipText("5 Hours");
        CaveFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaveFrameActionPerformed(evt);
            }
        });

        RiverFrame.setText("River");
        RiverFrame.setToolTipText("3 Hours");
        RiverFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiverFrameActionPerformed(evt);
            }
        });

        jbSwamp.setText("Swamp");
        jbSwamp.setToolTipText("1 Hour");
        jbSwamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSwampActionPerformed(evt);
            }
        });

        jButton4.setText("Volcano");
        jButton4.setToolTipText("3 Hours");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        forestFrame.setText("Forrest");
        forestFrame.setToolTipText("1 Hour");
        forestFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forestFrameActionPerformed(evt);
            }
        });

        TreehouseFrame.setText("Tree House");
        TreehouseFrame.setToolTipText("2 Hours");
        TreehouseFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreehouseFrameActionPerformed(evt);
            }
        });

        jButton8.setText("Valley");
        jButton8.setToolTipText("4 Hours");

        shoreFrame.setText("Shore");
        shoreFrame.setToolTipText("1Hour");
        shoreFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoreFrameActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hours Remaining:");

        time.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Logs:");

        logs.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("/10");

        javax.swing.GroupLayout blahLayout = new javax.swing.GroupLayout(blah);
        blah.setLayout(blahLayout);
        blahLayout.setHorizontalGroup(
            blahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blahLayout.createSequentialGroup()
                .addGroup(blahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(blahLayout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel1)
                        .addGap(98, 98, 98)
                        .addGroup(blahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(blahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                            .addComponent(logs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(blahLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel4)
                .addContainerGap())
            .addGroup(blahLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(blahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forestFrame)
                    .addComponent(CaveFrame)
                    .addComponent(RiverFrame)
                    .addComponent(jbSwamp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(blahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TreehouseFrame)
                    .addGroup(blahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton8)
                        .addComponent(shoreFrame))
                    .addComponent(jButton4))
                .addGap(143, 143, 143))
        );
        blahLayout.setVerticalGroup(
            blahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blahLayout.createSequentialGroup()
                .addGroup(blahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(blahLayout.createSequentialGroup()
                        .addGroup(blahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(blahLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(blahLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel4)
                                .addGap(0, 6, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blahLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(blahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(blahLayout.createSequentialGroup()
                                .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(blahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(logs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)))
                            .addGroup(blahLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)))
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(blahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CaveFrame)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(blahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSwamp)
                    .addComponent(TreehouseFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(blahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RiverFrame)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addGroup(blahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forestFrame)
                    .addComponent(shoreFrame))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(blah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(blah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forestFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forestFrameActionPerformed
        this.dispose();
        MapMenu mm = new MapMenu();
        mm.doAction("F");
        GameRun.getGame().setVisited(2);
    }//GEN-LAST:event_forestFrameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbSwampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSwampActionPerformed
        SwampChallenge sc = new SwampChallenge();
        sc.run();
    }//GEN-LAST:event_jbSwampActionPerformed

    private void RiverFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiverFrameActionPerformed
        this.dispose();
        MapMenu mm = new MapMenu();
        mm.doAction("R");
        GameRun.getGame().setVisited(3);
    }//GEN-LAST:event_RiverFrameActionPerformed

    private void CaveFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaveFrameActionPerformed
        this.dispose();
        CaveChallenge cc = new CaveChallenge();
        cc.run();
    }//GEN-LAST:event_CaveFrameActionPerformed

    private void shoreFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoreFrameActionPerformed
        
        int log = GameRun.getGame().getLogs();
        if (log == 10){
            this.dispose();
            ShoreFrame sf = new ShoreFrame();
            sf.setVisible(true);
            
        }
        else{
            JOptionPane.showMessageDialog(this, "You do not have 10 or more logs yet.",
            "Not enough logs", JOptionPane.ERROR_MESSAGE);
            //return;
                }
    }//GEN-LAST:event_shoreFrameActionPerformed

    private void TreehouseFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TreehouseFrameActionPerformed
        MapMenu mm = new MapMenu();
        mm.doAction("T");
        GameRun.getGame().setVisited(7);
    }//GEN-LAST:event_TreehouseFrameActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MapFrame().setVisible(true);
//               
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CaveFrame;
    private javax.swing.JButton RiverFrame;
    private javax.swing.JButton TreehouseFrame;
    private javax.swing.JPanel blah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton forestFrame;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbSwamp;
    private javax.swing.JLabel logs;
    private javax.swing.JButton shoreFrame;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
